version: '3.9'

services:
  forum_db:
    image: mysql/mysql-server:8.0
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: 'forum'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3308:3306"

  forum_mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "1025:1025"
        - "8025:8025"

  forum_keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      DB_VENDOR: 'postgres'
      DB_ADDR: 'keycloak_db'
      POSTGRES_DB: 'keycloak'
      DB_USER: 'keycloak'
      DB_PASSWORD: 'password'
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/themes/uhub
    depends_on:
      - forum_keycloak_db

  forum_keycloak_db:
    image: postgres:13.2
    ports:
      - "9990:5432"
    environment:
      POSTGRES_USER: 'keycloak'
      POSTGRES_DB: 'keycloak'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./keycloak/db:/var/lib/postgresql/data

networks:
  default:
    name: 'forum-network'
