ALTER TABLE `forum`.`T_POST` MODIFY COLUMN `FILE_URL` BLOB;
ALTER TABLE `forum`.`T_POST` MODIFY COLUMN `USER_ID` INT DEFAULT 0;
ALTER TABLE `forum`.`T_POST` RENAME COLUMN `FILE_URL` TO `FILE`;

ALTER TABLE `forum`.`T_COMMENT` MODIFY COLUMN `FILE_URL` BLOB;
ALTER TABLE `forum`.`T_COMMENT` MODIFY COLUMN `USER_ID` INT DEFAULT 0;
ALTER TABLE `forum`.`T_COMMENT` RENAME COLUMN `FILE_URL` TO `FILE`;